[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "airo-tulip"
version = "0.5.0"
authors = [
  { name = "Mathieu De Coster", email = "mathieu.decoster@ugent.be" },
  { name = "Thomas Van Acker", email = "thovacke.vanacker@ugent.be" }
]
description = "Client and API contract for controlling the KELO Robile platform (see airo-tulip-hal for the hardware abstraction layer)."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

dependencies = [
  "loguru>=0.7.2",
  "numpy",
  "eclipse-zenoh>=1.0.0",
  "msgpack>=1.0.0",
  "airo-typing>=2025.4.0"
]

[project.urls]
Homepage = "https://github.com/airo-ugent/airo-tulip"
Issues = "https://github.com/airo-ugent/airo-tulip/issues"

[tools.setuptools]
packages = ["airo_tulip"]
